### ISSUE TITLE
时钟的字体太大了，如何改小

### ISSUE THREAD

**Issue by wdxinren** [0111/Kindle_WeatherCN#1]
如题，不管横屏还是竖屏，时间的文本超过了Kindle的边界，看不全

**Comment by caterqiu** [comment]
> 如题，不管横屏还是竖屏，时间的文本超过了Kindle的边界，看不全
修改kindle.css，找到对应的对象 修改 font.size
![修改CSS](https://user-images.githubusercontent.com/5879898/209471590-42a7f209-0f01-4047-9cd5-bd39c4717693.png)
